/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.idiomatic.gradle.api;

import com.example.idiomatic.gradle.fixtures.TestIgService;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class IgApiTest {

    @Test
    void testMemberService() {
        IgApi api = new IgApi(new TestIgService());

        assertEquals(TestIgService.testData, api.getAllMembers());
    }
}
